version: '3.3'
services:
  web:
    image: rest-api-app
    command: npm run watch
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    command: redis-server
